aws_region                   = "us-east-1"
environment                  = "dev"
project_name                 = "ai-travel"
cluster_name                 = "ai-travel-dev"
cluster_version              = "1.30"
vpc_cidr                     = "10.1.0.0/16"
availability_zones           = ["us-east-1a", "us-east-1b"]
node_group_min_size          = 1
node_group_desired_size      = 2
node_group_max_size          = 3
node_instance_types          = ["t3.small"]
node_disk_size               = 30
db_instance_class            = "db.t3.micro"
db_allocated_storage         = 20
db_max_allocated_storage     = 50
db_name                      = "ai_travel_dev"
db_username                  = "aitravel_admin"
db_backup_retention_days     = 1
ecr_repositories             = ["frontend", "ai-service", "travel-service", "user-service", "utility-service"]
acm_certificate_domain       = "dev-api.invest-iq.online"
alert_email                  = "tkpreethi973@gmail.com"
finops_sender_email          = "tkp4762@gmail.com"
log_retention_days           = 3
github_org                   = "Plan-My-Journey"
github_repo                  = "planmyjourney-terraform"
k8s_namespace                = "dev"
cognito_domain_prefix        = "planmyjourney-dev"
frontend_domain              = "dev.invest-iq.online"
frontend_acm_certificate_arn = "arn:aws:acm:us-east-1:235270183260:certificate/91b9e8c2-6c81-4e7c-819c-34fb260aa246"
cognito_callback_urls        = ["https://dev.invest-iq.online/callback", "http://localhost:5173/callback"]
cognito_logout_urls          = ["https://dev.invest-iq.online/", "http://localhost:5173/"]
